[tool.ruff]
ignore = [
    "E501",
]
line-length = 119
extend-select = [
    "C9",
    "COM",
    "E",
    "F",
    "I",
    "W",
]

[tool.ruff.mccabe]
max-complexity = 8

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "citadel.settings"
norecursedirs = ["bower_components", "node_modules", ".git"]
env = ["PYTEST = true"]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]
