# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ulid2


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cicore', '0007_round_accepting_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, editable=False, primary_key=True, serialize=False)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cicore.Entry')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cicore.Round')),
            ],
        ),
    ]
