# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='slug',
            field=models.SlugField(default='xxx', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
