# Generated by Django 1.11.1 on 2017-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cicore", "0002_round_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="asset",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("round", "name")},
        ),
    ]
