# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cicore", "0003_asset_better"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="nonce",
            field=models.CharField(default="xxxxxxx", max_length=64, unique=True, editable=False),
            preserve_default=False,
        ),
    ]
