# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicore', '0004_entry_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='accepting_entries',
            field=models.BooleanField(default=True),
        ),
    ]
