# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cicore", "0006_round_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="accepting_votes",
            field=models.BooleanField(default=False),
        ),
    ]
