name: Build Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
